# style name or JSON path (default "auto")
#style: "~/AppData/Local/glow/Config/cyberwave.json"
style: "auto"
# mouse support (TUI-mode only)
mouse: false
# use pager to display markdown
pager: false
# word-wrap at width
width: 80
# show all files, including hidden and ignored.
all: false
