account = "+18652874495"
signal_cli_path = "signal-cli"
download_dir = "/home/christopher/signal-downloads"
notify_direct = true
notify_group = true
desktop_notifications = true
notification_preview = "full"
clipboard_clear_seconds = 30
inline_images = true
show_link_previews = true
native_images = false
date_separators = true
show_receipts = true
color_receipts = true
nerd_fonts = true
emoji_to_text = false
show_reactions = true
reaction_verbose = false
send_read_receipts = true
mouse_enabled = true
sidebar_on_right = false
theme = "Default"
keybinding_profile = "Default"
settings_profile = "Default"
proxy = ""
