general:
  # Commands to run when the WM has started
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "10px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "50px"
    right: "10px"
    bottom: "10px"
    left: "10px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    border:
      enabled: true
      color: "#8dbcff"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "95%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: true
      shown_on_top: true

    fullscreen:
      maximized: false
      shown_on_top: true

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "EXCEL" }
        window_class: { not_regex: "XLMAIN" }
      - window_process: { equals: "WINWORD" }
        window_class: { not_regex: "OpusApp" }
      - window_process: { equals: "POWERPNT" }
        window_class: { not_regex: "PPTFrameClass" }
      - window_title: { equals: "Command Palette" }
        window_class: { equals: "WinUIDesktopWin32WindowClass" }

# Hyper = Ctrl+Alt+Shift+F24
binding_modes:
  # Move Mode: bare hjkl / Arrows move the focused window; Esc/Enter exits
  - name: "move"
    keybindings:
      - commands: ["move --direction up"]
        bindings: ["k", "up"]
      - commands: ["move --direction left"]
        bindings: ["h", "left"]
      - commands: ["move --direction down"]
        bindings: ["j", "down"]
      - commands: ["move --direction right"]
        bindings: ["l", "right"]
      - commands: ["wm-disable-binding-mode --name move"]
        bindings: ["escape", "enter"]

  # Resize Mode: bare hjkl / Arrows resize in 50px steps; Shift = 10px; Esc/Enter exits
  - name: "resize"
    keybindings:
      # 50px coarse steps
      - commands: ["resize --height -50px"]
        bindings: ["k", "up"]
      - commands: ["resize --width -50px"]
        bindings: ["h", "left"]
      - commands: ["resize --height +50px"]
        bindings: ["j", "down"]
      - commands: ["resize --width +50px"]
        bindings: ["l", "right"]

      # 10px fine steps with Shift
      - commands: ["resize --height -10px"]
        bindings: ["shift+k", "shift+up"]
      - commands: ["resize --width -10px"]
        bindings: ["shift+h", "shift+left"]
      - commands: ["resize --height +10px"]
        bindings: ["shift+j", "shift+down"]
      - commands: ["resize --width +10px"]
        bindings: ["shift+l", "shift+right"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Minimize window
  - command: ["toggle-minimized"]
    binding: ["ctrl+alt+shift+F24+n"]

  # Quit application (close the entire process)
  - command: ["close"]
    binding: ["ctrl+alt+shift+F24+q"]

  # Launch Warp
  - commands: ["shell-exec C:/Users/chris/AppData/Local/Programs/Warp/Warp.exe"]
    bindings: ["ctrl+alt+shift+F24+enter"]

    # Hyper+X → Windows Settings
  - commands: ["shell-exec explorer.exe ms-settings:"]
    bindings: ["ctrl+alt+shift+F24+x"]

  # Focus (Hyper + WASD / Arrows)
  - commands: ["focus --direction left"]
    bindings: ["ctrl+alt+shift+F24+h", "ctrl+alt+shift+F24+left"]
  - commands: ["focus --direction right"]
    bindings: ["ctrl+alt+shift+F24+l", "ctrl+alt+shift+F24+right"]
  - commands: ["focus --direction up"]
    bindings: ["ctrl+alt+shift+F24+k", "ctrl+alt+shift+F24+up"]
  - commands: ["focus --direction down"]
    bindings: ["ctrl+alt+shift+F24+j", "ctrl+alt+shift+F24+down"]

    # Workspaces (Hyper + 1/2/3)
  - commands: ["focus --workspace 1"]
    bindings: ["control+alt+shift+F24+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["control+alt+shift+F24+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["control+alt+shift+F24+3"]

    # Layout toggle (vertical <-> horizontal)
  - commands: ["toggle-tiling-direction"]
    bindings: ["control+alt+shift+F24+v"]

  # Reset workspace (Hyper + 0): return to tiling, horizontal, redraw
  - commands: ["set-tiling", "wm-redraw"]
    bindings: ["control+alt+shift+F24+0"]

  # Fullscreen toggle (Hyper + F)
  - commands: ["toggle-fullscreen"]
    bindings: ["control+alt+shift+F24+f"]

  # Toggle float/tile for focused window (Hyper + ;)
  - commands: ["toggle-floating"]
    bindings: ["control+alt+shift+F24+oem_semicolon"]

  # Modes: Move Mode (sticky until Esc)
  - commands: ["wm-enable-binding-mode --name move"]
    bindings: ["control+alt+shift+F24+m"]

  # Modes: Resize Mode (sticky until Esc)
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["control+alt+shift+F24+r"]
