theme = "cyberwave"

[editor]
line-number = "relative"
cursorline = true # Highlights current line.
auto-save = true # Saves files on focus loss.

[editor.cursor-shape]
insert = "bar" # Cursor shape in insert mode.
normal = "block" # Cursor shape in normal mode.

[editor.shell]
program = "pwsh"
args = ["-NoExit", "-ExecutionPolicy", "Bypass", "-Command", ". $PROFILE;"]

[keys.normal]
C-s = ":write" # Quick save.
