configpath: /Users/chris/Library/Application Support/nom/config.yml
version: ""
feed_backends:
    - name: miniflux
      type: miniflux
      url: "https://miniflux.theantichris.com"
ordering: asc
filtering:
    defaultIncludeFeedName: false
theme:
    glamour: dark
    titleColor: "62"
    titleColorFg: "231"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
