#!/data/data/com.termux/files/usr/bin/bash

set -u

clear
fastfetch

printf '\n'
read -r -p 'Press Enter to return home...'

am start -a android.intent.action.MAIN -c android.intent.category.HOME >/dev/null 2>&1
