#!/data/data/com.termux/files/usr/bin/bash

set -u

MAGENTA='\033[38;2;202;1;116m'
CYAN='\033[38;2;0;240;255m'
GREEN='\033[38;2;0;255;156m'
YELLOW='\033[38;2;255;211;0m'
RESET='\033[0m'

clear
printf '%bDECK // PING%b\n\n' "$MAGENTA" "$RESET"

read -r -p 'Target [1.1.1.1]: ' target
target=${target:-1.1.1.1}

printf '\n%bTarget%b  %s\n\n' "$CYAN" "$RESET" "$target"

if ping -c 4 "$target"; then
  printf '\n%bReachable%b\n' "$GREEN" "$RESET"
else
  printf '\n%bNo response.%b\n' "$YELLOW" "$RESET"
fi

printf '\n'
read -r -p 'Press Enter to return home...'

am start -a android.intent.action.MAIN -c android.intent.category.HOME >/dev/null 2>&1
