# Cyberwave

# Code syntax highlight theme
code_syntax_highlight = "monokai"

# ========= Border =========
file_panel_border = "#029fec91"
sidebar_border = "#08252f"
footer_border = "#029fec91"

# ========= Border Active =========
file_panel_border_active = "#16e6c9"
sidebar_border_active = "#c73df5e3"
footer_border_active = "#23d18b"
modal_border_active = "#ff8ffd"

# ========= Background (bg) =========
full_screen_bg = "#091a1f"
file_panel_bg = "#001a24"
sidebar_bg = "#08252f"
footer_bg = "#192a30"
modal_bg = "#192a30"

# ========= Foreground (fg) =========
full_screen_fg = "#cdcefb"
file_panel_fg = "#bdc2c3"
sidebar_fg = "#8e9395"
footer_fg = "#bdc2c3"
modal_fg = "#cdcefb"

# ========= Special Color =========
cursor = "#16e6c9"
correct = "#23d18b"
error = "#e25e44"
hint = "#75beff"
cancel = "#ff8ffd"

# Gradient color can only have two colors!
gradient_color = ["#16e6c9", "#c73df5e3"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#23d18b"
file_panel_top_path = "#16e6c9"
file_panel_item_selected_fg = "#cdcefb"
file_panel_item_selected_bg = "#264f78"

# ========= Sidebar Special Items =========
sidebar_title = "#c73df5e3"
sidebar_item_selected_fg = "#cdcefb"
sidebar_item_selected_bg = "#264f78"
sidebar_divider = "#5b3199bf"

# ========= Modal Special Items =========
modal_cancel_fg = "#cdcefb"
modal_cancel_bg = "#e25e44"
modal_confirm_fg = "#091a1f"
modal_confirm_bg = "#23d18b"

# ========= Help Menu =========
help_menu_hotkey = "#26add0"
help_menu_title = "#16e6c9"
