# Cyberwave Theme for SuperFile

# Code syntax highlight theme
code_syntax_highlight = "monokai"

# ========= Border Colors =========
file_panel_border = "#44475a"             # border (subtle gray)
sidebar_border = "#44475a"                # consistent border
footer_border = "#44475a"                 # matching borders

# ========= Active Border Colors =========
file_panel_border_active = "#00f5ff"      # primary (electric cyan glow)
sidebar_border_active = "#bd93f9"         # accent (bright purple)
footer_border_active = "#00f5ff"          # primary (electric cyan)
modal_border_active = "#ff0080"           # accent-2 (hot magenta)

# ========= Background Colors =========
full_screen_bg = "#0d0221"                # background (deep purple-black)
file_panel_bg = "#16213e"                 # surface-2 (blue-purple content)
sidebar_bg = "#1a1b26"                    # surface-1 (panel background)
footer_bg = "#16213e"                     # surface-2 (matches file panel)
modal_bg = "#2a1f3d"                      # surface-3 (highest contrast)

# ========= Foreground Colors =========
full_screen_fg = "#e0e6ff"                # text (bright blue-white)
file_panel_fg = "#c9d1d9"                 # text-muted (dimmer white)
sidebar_fg = "#a9b1d6"                    # sidebar specific (muted blue)
footer_fg = "#c9d1d9"                     # text-muted (consistent)
modal_fg = "#e0e6ff"                      # text (bright for modals)

# ========= Special State Colors =========
cursor = "#00f5ff"                        # primary (electric cyan cursor)
correct = "#39ff14"                       # success (electric lime green)
error = "#ff073a"                         # error (hot red)
hint = "#8be9fd"                          # info (light cyan)
cancel = "#ff0080"                        # accent-2 (hot magenta)

# ========= Gradient Colors =========
# Electric cyan to bright purple - signature cyber wave
gradient_color = ["#00f5ff", "#bd93f9"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#39ff14" # success (electric green for dirs)
file_panel_top_path = "#00f5ff"           # primary (electric cyan path)
file_panel_item_selected_fg = "#ffffff"   # pure white for selection text
file_panel_item_selected_bg = "#44475a"   # selection (dark gray selection)

# ========= Sidebar Special Items =========
sidebar_title = "#bd93f9"                 # accent (bright purple titles)
sidebar_item_selected_fg = "#ffffff"      # pure white selection text
sidebar_item_selected_bg = "#44475a"      # selection (consistent selection)
sidebar_divider = "#6272a4"               # comment (visible divider)

# ========= Modal Special Items =========
modal_cancel_fg = "#ffffff"               # white text on colored bg
modal_cancel_bg = "#ff073a"               # error (hot red for cancel)
modal_confirm_fg = "#0d0221"              # background (dark text for contrast)
modal_confirm_bg = "#00f5ff"              # primary (electric cyan confirm)

# ========= Help Menu Colors =========
help_menu_hotkey = "#bd93f9"              # accent (purple for hotkeys)
help_menu_title = "#00f5ff"               # primary (electric cyan titles)

# ========= File Type Colors (Cyber Wave Style) =========
directory_color = "#00f5ff"               # primary (electric cyan directories)
executable_color = "#39ff14"              # success (electric green executables)
archive_color = "#ffb86c"                 # warning (orange archives)
image_color = "#ff0080"                   # accent-2 (hot magenta images)
video_color = "#bd93f9"                   # accent (bright purple videos)
audio_color = "#ff079a"                   # hot pink audio files
document_color = "#8be9fd"                # info (light cyan documents)
config_color = "#f1fa8c"                  # electric yellow configs
log_color = "#6272a4"                     # comment (muted for logs)
temp_color = "#44475a"                    # border (gray for temp files)

# ========= Additional Cyber Elements =========
# File extension specific colors for enhanced visual hierarchy
code_file_color = "#50fa7b"               # link (bright green for code)
markup_file_color = "#ff79c6"             # hot pink for markup
data_file_color = "#8be9fd"               # light cyan for data files
system_file_color = "#6272a4"             # comment (muted for system)
hidden_file_color = "#44475a"             # border (subtle for hidden)
symlink_color = "#bd93f9"                 # accent (purple for symlinks)
