# Cyberwave theme for Helix

"ui.background" = { bg = "background" }
"ui.background.separator" = "border"
"ui.cursor" = { fg = "background", bg = "primary" }
"ui.cursor.normal" = { fg = "background", bg = "primary" }
"ui.cursor.insert" = { fg = "background", bg = "secondary" }
"ui.cursor.select" = { fg = "background", bg = "tertiary" }
"ui.cursor.match" = { fg = "background", bg = "quaternary" }
"ui.cursor.primary" = { fg = "background", bg = "primary" }
"ui.cursor.secondary" = { fg = "background", bg = "secondary" }
"ui.cursorline.primary" = { bg = "surface-1" }
"ui.cursorline.secondary" = { bg = "surface-2" }
"ui.cursorcolumn.primary" = { bg = "surface-1" }
"ui.cursorcolumn.secondary" = { bg = "surface-2" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"ui.linenr" = "comment"
"ui.linenr.selected" = "text"
"ui.statusline" = { fg = "text", bg = "surface-1" }
"ui.statusline.inactive" = { fg = "text-muted", bg = "surface-2" }
"ui.statusline.normal" = { fg = "background", bg = "primary" }
"ui.statusline.insert" = { fg = "background", bg = "secondary" }
"ui.statusline.select" = { fg = "background", bg = "tertiary" }
"ui.statusline.separator" = "border"
"ui.popup" = { fg = "text", bg = "surface-2" }
"ui.popup.info" = { fg = "text", bg = "surface-2" }
"ui.window" = { bg = "surface-1" }
"ui.help" = { fg = "text", bg = "surface-2" }
"ui.text" = "text"
"ui.text.focus" = "text"
"ui.text.inactive" = "text-muted"
"ui.text.info" = "info"
"ui.virtual" = "comment"
"ui.virtual.ruler" = { bg = "surface-1" }
"ui.virtual.whitespace" = "comment"
"ui.virtual.indent-guide" = "comment"
"ui.virtual.inlay-hint" = { fg = "comment", modifiers = ["italic"] }
"ui.virtual.inlay-hint.parameter" = { fg = "comment", modifiers = ["italic"] }
"ui.virtual.inlay-hint.type" = { fg = "comment", modifiers = ["italic"] }
"ui.virtual.wrap" = "comment"
"ui.virtual.jump-label" = { fg = "highlight", modifiers = ["bold"] }
"ui.menu" = { fg = "text", bg = "surface-2" }
"ui.menu.selected" = { fg = "text", bg = "selection" }
"ui.menu.scroll" = { fg = "text", bg = "surface-1" }
"ui.highlight" = { bg = "selection" }
"ui.highlight.frameline" = { bg = "error" }
"ui.debug" = { fg = "error" }
"ui.debug.breakpoint" = { fg = "error" }
"ui.debug.active" = { fg = "warning" }

"warning" = "warning"
"error" = "error"
"info" = "info"
"hint" = "tertiary"
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.hint" = { fg = "tertiary", modifiers = ["underlined"] }
"diagnostic.info" = { fg = "info", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "warning", modifiers = ["underlined"] }
"diagnostic.error" = { fg = "error", modifiers = ["underlined"] }

"comment" = "comment"
"constant" = "secondary"
"constant.builtin" = "secondary"
"constant.character" = "secondary"
"constant.character.escape" = "tertiary"
"constant.macro" = "tertiary"
"constant.numeric" = "secondary"
"constructor" = "tertiary"
"diff.delta" = "warning"
"diff.minus" = "error"
"diff.plus" = "success"
"function" = "tertiary"
"function.builtin" = "tertiary"
"function.macro" = "quaternary"
"function.method" = "tertiary"
"function.special" = "quaternary"
"keyword" = "text"
"keyword.control" = "quaternary"
"keyword.control.conditional" = "quaternary"
"keyword.control.exception" = "quaternary"
"keyword.control.import" = "quaternary"
"keyword.control.repeat" = "quaternary"
"keyword.control.return" = "quaternary"
"keyword.directive" = "quaternary"
"keyword.function" = "quaternary"
"keyword.operator" = "quaternary"
"keyword.storage" = "text"
"keyword.storage.modifier" = "text"
"keyword.storage.type" = "primary"
"label" = "primary"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "primary", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "link"
"markup.link.url" = { fg = "link", modifiers = ["underlined"] }
"markup.list" = "text"
"markup.quote" = "comment"
"markup.raw" = "secondary"
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"namespace" = "primary"
"operator" = "quaternary"
"property" = "primary"
"punctuation" = "text"
"punctuation.bracket" = "text"
"punctuation.delimiter" = "text"
"punctuation.special" = "quaternary"
"string" = "secondary"
"string.escape" = "tertiary"
"string.regex" = "quaternary"
"string.special" = "tertiary"
"tag" = "primary"
"tag.builtin" = "primary"
"type" = "type-color"
"type.builtin" = "type-color"
"type.enum.variant" = "type-color"
"variable" = "primary"
"variable.builtin" = "primary"
"variable.other.member" = "primary"
"variable.parameter" = "text"

[palette]
# Base colors from cyberwave_palette.json
background = "#091a1f"
surface-1 = "#192a30"
surface-2 = "#001a24"
surface-3 = "#08252f"
text = "#cdcefb"
text-muted = "#bdc2c3"
comment = "#8e9395"

# Accent colors
primary = "#16e6c9"
secondary = "#26add0"
tertiary = "#c73df5e3"
quaternary = "#ff8ffd"

# Semantic colors
success = "#23d18b"
warning = "#cca700"
error = "#e25e44"
info = "#75beff"
link = "#119c82"

# UI colors
border = "#029fec91"
shadow = "#5b3199bf"
selection = "#264f78"
highlight = "#ff349a"

# Syntax colors
type-color = "#b3f971"
